services:
  - type: web
    name: voice-distress-system
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/manage.py migrate --noinput && gunicorn --chdir backend config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
