# Generated by Django 6.0.6 on 2026-06-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.CharField(max_length=255)),
                ('distress_keyword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('ai_explanation', models.TextField()),
                ('voice_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distress_app.voiceevent')),
            ],
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sent', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distress_app.emergencycontact')),
                ('voice_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distress_app.voiceevent')),
            ],
        ),
    ]
