# Generated by Django 6.0.6 on 2026-06-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
