# Generated by Django 6.0.6 on 2026-06-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0002_alertlog_user_id_emergencycontact_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
