# Generated by Django 6.0.6 on 2026-06-29 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0003_emergencycontact_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distress_app.emergencycontact'),
        ),
    ]
