# Generated by Django 6.0.6 on 2026-06-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0003_triggerword'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='test-user', max_length=100, unique=True)),
                ('word', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
