# Generated by Django 6.0.6 on 2026-06-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0004_triggerword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='test-user', max_length=100, unique=True)),
                ('threshold', models.IntegerField(default=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='voiceevent',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='voiceevent',
            name='distress_keyword',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='alert_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='base_risk_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='classification',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='intensity_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='send_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='telegram_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='trigger_phrase_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='user_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceevent',
            name='user_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
    ]
