# Merge migration to resolve conflicting branches
# Generated by Django on 2026-06-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0004_alter_alertlog_contact'),
        ('distress_app', '0005_riskthreshold_remove_voiceevent_audio_file_and_more'),
    ]

    operations = [
        # This is a merge migration, no operations needed
    ]