# Generated by Django 6.0.6 on 2026-07-02 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('transcription', models.TextField()),
                ('voice_features', models.JSONField(default=dict)),
                ('text_score', models.FloatField()),
                ('voice_score', models.FloatField()),
                ('text_confidence', models.FloatField()),
                ('voice_confidence', models.FloatField()),
                ('final_risk_score', models.FloatField()),
                ('alert_triggered', models.BooleanField(default=False)),
                ('label', models.CharField(db_index=True, max_length=20)),
                ('dataset_version', models.CharField(default='v1.0.0', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'label'], name='distress_ap_timesta_3acd91_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('ai_explanation', models.TextField()),
                ('voice_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distress_app.voiceevent')),
            ],
        ),
    ]
