# Generated by Django 6.0.6 on 2026-07-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0007_alter_emergencycontact_telegram_chat_id_inferencelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertlog',
            name='delivery_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.TextField(blank=True, default='')),
                ('voice_features', models.JSONField(blank=True, default=dict)),
                ('risk_score', models.FloatField(default=0.0)),
                ('classification', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('alert_message', models.TextField(blank=True, default='')),
                ('alert_triggered', models.BooleanField(default=False)),
                ('telegram_delivery_status', models.BooleanField(default=False)),
                ('contacts_notified', models.IntegerField(default=0)),
                ('contacts_successful', models.IntegerField(default=0)),
                ('contacts_failed', models.IntegerField(default=0)),
                ('incident_status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved'), ('False Alarm', 'False Alarm')], default='Open', max_length=20)),
                ('inference_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='distress_app.inferencelog')),
                ('voice_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='distress_app.voiceevent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alertlog',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_logs', to='distress_app.incident'),
        ),
    ]
