# Generated by Django 6.0.6 on 2026-07-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distress_app', '0007_triggerword_is_active'),
        ('distress_app', '0009_emergencycontact_created_at'),
    ]

    operations = [
    ]
